### A starting notebook for homework 4

The next line activates the environment in which we are working on HW4. It is assumed that you already generated this environment, per the instructions in the document *UsingJulia.pdf*

In [1]:
using Pkg
Pkg.activate("/Users/jeff/Dropbox/MAE250H/julia/development/HW4")

"/Users/jeff/Dropbox/MAE250H/julia/development/HW4/Project.toml"

These load in some packages useful for this notebook

In [2]:
using Revise
using Plots
using LinearAlgebra
using HW4

┌ Info: Recompiling stale cache file /Users/jeff/.julia/compiled/v1.1/HW4/enQ9F.ji for HW4 [59be1dea-6512-11e9-2444-99050c21919d]
└ @ Base loading.jl:1184


### Using 2-D data types (revisited)

The data types are slightly more powerful that those we introduced in HW2. We have added direct indexing, as we did on 1-d data types in the previous homework. We have also created a few other "nodes" in the type tree. It now looks like this:

                                    |-> CellData
                 |->  ScalarData -> |-> NodeData
     GridData -> |                  |-> XEdgeData
                 |                  |-> YEdgeData
                 |
                 |->  VectorData    |-> EdgeData (with fields XEdgeData, YEdgeData)
                 
All of the ScalarData types are endowed with direct indexing. This includes the components of edge data (but not edge data itself). All of these types share the same parameters {NX,NY} so they are "aware" of the grid that they lie on.

Now we have endowed our cell and node data types with the direct indexing that we used on 1-d types in the previous homework. We have also exported all of the data types so we do not need the annoying prefix "HW4" here:

In [3]:
w = ones(5,7)
p = CellData(w)
p[2,1] = 2
reverse(transpose(p),dims=1)

7×5 Array{Float64,2}:
 1.0  1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0  1.0
 1.0  2.0  1.0  1.0  1.0

In [4]:
p2 = CellData(p)

5×7 CellData{3,5}:
 0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0

In [7]:
q = EdgeData(p);

In [8]:
q.qx

4×7 XEdgeData{3,5}:
 0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0

In [9]:
q.qy

5×6 YEdgeData{3,5}:
 0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0

In [11]:
qxtranspose = transpose(q.qx)
qxtranspose[1,2] = 1.0
reverse(transpose(q.qx),dims=1)

7×4 Array{Float64,2}:
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0
 0.0  1.0  0.0  0.0

In [8]:
p = CellData(5,4)

7×6 CellData{5,4}:
 0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0

In [10]:
typeof(q) <: VectorData{3,5}

true

In [11]:
p2 = CellData(p)
p2 .= p

7×6 CellData{5,4}:
 0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0

In [12]:
p = CellData(ones(5,7))
p2 = -p
reverse(transpose(p2),dims=1)

7×5 Array{Float64,2}:
 -1.0  -1.0  -1.0  -1.0  -1.0
 -1.0  -1.0  -1.0  -1.0  -1.0
 -1.0  -1.0  -1.0  -1.0  -1.0
 -1.0  -1.0  -1.0  -1.0  -1.0
 -1.0  -1.0  -1.0  -1.0  -1.0
 -1.0  -1.0  -1.0  -1.0  -1.0
 -1.0  -1.0  -1.0  -1.0  -1.0

In [13]:
w = NodeData(p)
w[2,3] = 1.0
reverse(transpose(w),dims=1)

6×4 Array{Float64,2}:
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0
 0.0  1.0  0.0  0.0
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0

In [16]:
dot(p,p2)

-1.0

#### Interpolation between data types

Let's interpolate from cell data to edge data

In [45]:
p = CellData(5,3)
p .= 1:7
reverse(transpose(p),dims=1)

5×7 Array{Float64,2}:
 1.0  2.0  3.0  4.0  5.0  6.0  7.0
 1.0  2.0  3.0  4.0  5.0  6.0  7.0
 1.0  2.0  3.0  4.0  5.0  6.0  7.0
 1.0  2.0  3.0  4.0  5.0  6.0  7.0
 1.0  2.0  3.0  4.0  5.0  6.0  7.0

In [24]:
q = EdgeData(p)
interpolate!(q,p);

In [25]:
reverse(transpose(q.qx),dims=1)

5×6 Array{Float64,2}:
 1.5  2.5  3.5  4.5  5.5  6.5
 1.5  2.5  3.5  4.5  5.5  6.5
 1.5  2.5  3.5  4.5  5.5  6.5
 1.5  2.5  3.5  4.5  5.5  6.5
 1.5  2.5  3.5  4.5  5.5  6.5

In [23]:
reverse(transpose(q.qy),dims=1)

4×7 Array{Float64,2}:
 1.0  2.0  3.0  4.0  5.0  6.0  7.0
 1.0  2.0  3.0  4.0  5.0  6.0  7.0
 1.0  2.0  3.0  4.0  5.0  6.0  7.0
 1.0  2.0  3.0  4.0  5.0  6.0  7.0

Take the gradient of this data

In [43]:
q2 = gradient(p)
reverse(transpose(q2.qx),dims=1)

5×6 Array{Float64,2}:
 1.0  1.0  1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0  1.0  1.0

In [44]:
reverse(transpose(q2.qy),dims=1)

4×7 Array{Float64,2}:
 0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0

### Linear indexing

A useful feature of our data types is the ability to use linear indexing. Each scalar data type is like a 2-d array, but can also be accessed like a 1-d array. The array itself is stored column by column. But remember that each column of array data corresponds to a row in the grid. So elements in each horizontal row of the grid are naturally contiguous in memory.

Let's see how this works on CellData. First let's look at the full array:

In [53]:
p = CellData(5,3)
p .= 1:7
reverse(transpose(p),dims=1)

5×7 Array{Float64,2}:
 1.0  2.0  3.0  4.0  5.0  6.0  7.0
 1.0  2.0  3.0  4.0  5.0  6.0  7.0
 1.0  2.0  3.0  4.0  5.0  6.0  7.0
 1.0  2.0  3.0  4.0  5.0  6.0  7.0
 1.0  2.0  3.0  4.0  5.0  6.0  7.0

Now let us access elements the 2nd through 5th elements in the lower row.

In [57]:
p[2:5]

4-element Array{Float64,1}:
 2.0
 3.0
 4.0
 5.0

But if we desire to access vertical columns of the grid is contiguous chunks, we first have to transpose it. Let's inspect the first 7 entries in this transposed form to demonstrate this:

In [60]:
transpose(p)[1:7]

7-element Array{Float64,1}:
 1.0
 1.0
 1.0
 1.0
 1.0
 2.0
 2.0

Why is this important? Because it will save a lot of computational time if we can apply linear indexing on continguous memory. For example, when we wish to solve tridiagonal systems in each coordinate direction.